#!/bin/bash

function yard_main() {
    case "$1" in
        ssh) yard_ssh $2 ;;
        bash) yard_ssh $2 ;;
        mount) yard_mount $2 ;;
        umount) yard_umount $2 ;;
        mount-secret) yard_mount_secret $2 ;;
        umount-secret) yard_umount_secret $2 ;;
        exit
        *) echo "Expected command." ;;
    esac
}

function yard_ssh() {
    sshpass -p "YardCode" ssh yard@yard$1 -t "clear; bash"
}

function yard_mount() {
    mkdir -p $HOME/Yard$1 >/dev/null 2>&1
    echo "YardCode" | sshfs yard@yard$1:/home/yard $HOME/Yard$1 -o password_stdin
}

function yard_umount() {
    sudo umount $HOME/Yard$1
    sudo rmdir $HOME/Yard$1
}

function yard_mount_secret() {
    mkdir -p $HOME/Yard$1-secret >/dev/null 2>&1
    echo "YardCode" | sshfs yard@yard$1:/home/.secret $HOME/Yard$1-secret -o password_stdin
}

function yard_umount_secret() {
    sudo umount $HOME/Yard$1-secret
    sudo rmdir $HOME/Yard$1-secret
}

yard_main $1 $2 $3